### PR TITLE
Add backslashes to multiple line commands

### PR DESCRIPTION
**Pull request by schemacs**
Maybe [these two command](https://github.com/minio/mc/issues/4023#issuecomment-1072075566) should be updated too

### CODE REVIEW

**Comment by schemacs** [comment]
Is [this update](https://github.com/minio/docs/commit/ef30821063a2f20510bcce42e98a74b7222763f0#diff-98628c7f804651199688bb9997db151646d2a979c94ac2e1797e3934c165215dR214) correct too?

**Comment by ravindk89** [comment]
> Is [this update](https://github.com/minio/docs/commit/ef30821063a2f20510bcce42e98a74b7222763f0#diff-98628c7f804651199688bb9997db151646d2a979c94ac2e1797e3934c165215dR214) correct too?

You'll have to be more specific, that was a very large update to restructure our CLI docs (and there's another one incoming too so I hope no one is depending on those URL paths)

**Comment by ravindk89** [comment]
> Maybe [these two command](https://github.com/minio/mc/issues/4023#issuecomment-1072075566) should be updated too

See https://github.com/minio/docs/issues/446 for intended work in capturing and reducing the confusion these tutorials can create in their current form.

**Comment by schemacs** [comment]
> > Is [this update](https://github.com/minio/docs/commit/ef30821063a2f20510bcce42e98a74b7222763f0#diff-98628c7f804651199688bb9997db151646d2a979c94ac2e1797e3934c165215dR214) correct too?
> 
> You'll have to be more specific, that was a very large update to restructure our CLI docs (and there's another one incoming too so I hope no one is depending on those URL paths)

Sorry about this, the anchor in the url doesn't go to the specified lines in replication-overview.rst:

```diff
- object was created. You can use the :mc-cmd:`mc cp` command to create a 
+ object was created. You can use The command command to create a 
```

All right, let's arrange the work in #446 .

**Pull request closed without merging**
