### PR TITLE
Fix anchor scrolling issue on Webkit browsers

### PR DESCRIPTION
**Pull request by rushenn**

### CODE REVIEW

**Review by kaankabalak — APPROVED** [review]
LGTM & tested

**Review by djwfyi — CHANGES_REQUESTED** [review]
This fixes the scrolling issue, but we have a new issue with this PR that breaks retention of the reading mode and dark mode on Firefox.

To reproduce:

- Build this PR
- Open the site in Firefox
- activate dark mode and or reading mode
- Click on any link in the navigation

Page returns to the standard page view in light mode.

**Comment by djwfyi** [comment]
> This fixes the scrolling issue, but we have a new issue with this PR that breaks retention of the reading mode and dark mode on Firefox.
> 
> To reproduce:
> 
> * Build this PR
> * Open the site in Firefox
> * activate dark mode and or reading mode
> * Click on any link in the navigation
> 
> Page returns to the standard page view in light mode.

Seems to be due to viewing local files directly rather than through a web server.
Problem resolved after using a python server to view the pages instead.

**Review by djwfyi — APPROVED** [review]
LGTM

**Pull request merged**
