### PR TITLE
Update base theme to match the new website

### PR DESCRIPTION
**Pull request by rushenn**
**Note:** 

I’ve applied the base layer of the new skin in preparation for tomorrow’s launch. This is a temporary patch, so there are still many UI issues that need a more thorough code fix. Please disregard any minor to moderate UI issues for now. I’ll revisit and address these after the new website goes live.

Part of https://github.com/miniohq/min.io/issues/2474

Please hold off on merging until 13th, 06:00 PST.

### CODE REVIEW

**Comment by ravindk89** [comment]
http://192.241.195.202:9000/staging/new-theme/linux/index.html

http://192.241.195.202:9000/staging/new-theme/k8s/index.html

This looks fine to my eye. We can hold until tomorrow and then merge this in.

@rushenn i'm going to try to cherry-pick this over to the fork repo and see if that works as-is.

**Comment by ravindk89** [comment]
@rushenn the top nav imagery seems off, but if we want to hold off on dealing with that I'm OK

image

**Comment by rushenn** [comment]
@ravindk89 Do You mean the top-left background image?

**Comment by ravindk89** [comment]
whatever is on the right - if that design is intentional then we are good, no worries.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
