### PR TITLE
DOCS-309: MinIO Hybrid Cloud User Management

### LINKED ISSUE #309: MinIO Hybrid Cloud User Management
# Summary

Cover Identity and Access Management Concept + Tutorial for Hybrid Cloud.

# Completion Checklist

[ ] - User Management
[ ] - Group Management
[ ] - Policy Management
[ ] - External IDentity Providers (IDP)
[ ] - Encryption Placeholder

### PR DESCRIPTION
**Pull request by ravindk89**
Issue resolves #309 

# Summary

Document MinIO Console-based User, Group, and Policy management. Includes Service Account docs.

Key pages:

- http://127.0.0.1:8000/tutorials/user-management.html
- http://127.0.0.1:8000/tutorials/group-management.html
- http://127.0.0.1:8000/tutorials/policy-management.html

# Build Instructions

Clone, fetch, and checkout DOCS-309 branch. 

```py
python -m pip install --user virtualenv
python3 -m venv venv

source venv/bin/activate
pip install -r requirements.txt
make html
python -m http.server --directory build/DOCS-309/html
```

### CODE REVIEW

**Comment by cesnietor** [comment]
just a question on `User Management`:
```
3) Copy the Service Account Credentials
```
Should we also mention that if credentials are lost you will have to recreate the Service Account?

**Comment by ravindk89** [comment]
> just a question on `User Management`:
> 
> ```
> 3) Copy the Service Account Credentials
> ```
> 
> Should we also mention that if credentials are lost you will have to recreate the Service Account? Or is it implicit?

Oh, yes definitely. Also need to include that you cannot update the credentials *or* policy after creation. Will add that to next patch.

**Comment by cesnietor** [comment]
on `Group Management`:
```
Open the Group Management Interface: .... If the Admin navigation group is collapsed...
```
Should we mention that if the Admin page is not visible is because the user might not have enough permissions?

**Comment by cesnietor** [comment]
Apart from that everything looks neat!

**Review by cesnietor — APPROVED** [review]

**Comment by ravindk89** [comment]
> on `Group Management`:
> 
> ```
> Open the Group Management Interface: .... If the Admin navigation group is collapsed...
> ```
> 
> Should we mention that if the Admin page is not visible is because the user might not have enough permissions?

Yeah, I actually intend to go into a lot more detail in the security collapsible as far as the exact perms needed in a second pass. For now I will definitely make that explicit.

**Review by dvaldivia — APPROVED** [review]

**Review by Alevsk — APPROVED** [review]
LGTM / tested

**Pull request merged**
