### PR TITLE
Replace Algolia DocSearch with InstantSearch

### PR DESCRIPTION
**Pull request by rushenn**
- Rendered only the relevant search results that has the match-level of either `full` or `partial`.
- Added refinements to display results from other platforms (Active platform is selected by default). 
- Better title and hierarchical display.
title

- Added icons to represent the hierarchy level.
icons
- Relevant results on full/partial match queries.
Screenshot 2022-10-27 at 12 09 26

- TODO: Keyboard shortcut to trigger/focus the search modal. (Will address this with a new PR)

### CODE REVIEW

**Comment by rushenn** [comment]
@djwfyi @ravindk89 PR is ready to review, would appreciate it if you could take a look.

**Comment by rushenn** [comment]
@ravindk89 @djwfyi Added platform indicator on search results. If there are more than one filters selected, the platform label will be visible. Please take a look and let me know if you have any feedback. 

Screenshot 2022-10-31 at 19 33 36

**Comment by ravindk89** [comment]
I think this is a solid move forward. We can play with the algorithm and see what we can get out of it as far as ordering goes.

@djwfyi if you didn't notice anything odd on your end lets merge this

**Comment by rushenn** [comment]
@ravindk89 @djwfyi Marking this PR as WIP, as I found an issue with the escape key behaviour. Will fix it and let you know for further review.

**Comment by rushenn** [comment]
@ravindk89 @djwfyi PR is ready for review, PTAL.

**Review by djwfyi — APPROVED** [review]
This is great!
LGTM!

**Pull request merged**
