### PR TITLE
Implement Algolia search

### PR DESCRIPTION
**Pull request by rushenn**
Fixes https://github.com/minio/docs/issues/552

### CODE REVIEW

**Comment by ravindk89** [comment]
@rushenn you might have to re-create this against `main`, for some reason the migration from `docs-ia` to `main` simply closed all PRs

**Comment by rushenn** [comment]
@ravindk89 PR is back it seems, thanks to Harsha!

**Review by djwfyi — CHANGES_REQUESTED** [review]
Search integration looks good.

However, I noticed that when switching pages, the reader and dark mode options are not retained. A user has to reselect them any time they go to a new page.
Can we fix that?

**Comment by djwfyi** [comment]
For anyone else testing this, the Algolia crawler has not yet updated to the new URLs, so all results are for docs.min.io.

**Comment by rushenn** [comment]
@djwfyi 

> However, I noticed that when switching pages, the reader and dark mode options are not retained. A user has to reselect them any time they go to a new page.
Can we fix that?

I'm unable to replicate this issue. Do you see any errors in the console?

**Comment by djwfyi** [comment]
@rushenn 

The choices are retained in Google Chrome and Safari, but not in Firefox.

**Comment by rushenn** [comment]
@djwfyi 

Tested on Firefox 104, 103 and 102 on macOS, Windows and Linux. I'm still unable to replicate the issue. 

Can you provide your OS/browser version please?  I will keep test and try to find out the issue.

**Comment by djwfyi** [comment]
Weird.
Firefox 104.0.2
OS X Monterey 12.5.1
M1 Pro

Cookie warnings:

```
Some cookies are misusing the recommended “SameSite“ attribute 8
Cookie “_ga” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [inject.js:1456:23](moz-extension://1d82fc16-7054-4bf4-9c34-47199e0b51f2/public/js/inject.js)
Cookie “_gid” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [inject.js:1456:23](moz-extension://1d82fc16-7054-4bf4-9c34-47199e0b51f2/public/js/inject.js)
Cookie “_ga” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [inject.js:1478:39](moz-extension://1d82fc16-7054-4bf4-9c34-47199e0b51f2/public/js/inject.js)
Cookie “_gd1663186968720” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [inject.js:1456:23](moz-extension://1d82fc16-7054-4bf4-9c34-47199e0b51f2/public/js/inject.js)
Cookie “_lo_uid” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [inject.js:1456:23](moz-extension://1d82fc16-7054-4bf4-9c34-47199e0b51f2/public/js/inject.js)
Cookie “_gd1663186968720” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [inject.js:1456:23](moz-extension://1d82fc16-7054-4bf4-9c34-47199e0b51f2/public/js/inject.js)
Cookie “_lorid” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [inject.js:1456:23](moz-extension://1d82fc16-7054-4bf4-9c34-47199e0b51f2/public/js/inject.js)
Cookie “_lo_uid” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

**Comment by ravindk89** [comment]
@djwfyi I just approved your PR fixing up the baseURLs. 

Once we merge that, we should be able to further test this PR and see if the search works (I assume?)

**Pull request merged**
