### PR TITLE
Fix white-space behaviour of inline code blocks

### PR DESCRIPTION
**Pull request by rushenn**

### CODE REVIEW

**Comment by rushenn** [comment]
@Ravind Apologise for the late reply, somehow I missed the notification for the Slack thread. 

I've added a potential solution for extremely long code blocks within table cells. Please let me know if this resolves the issue for you

**Comment by ravindk89** [comment]
This is definitely _better_.

Granted for the very long metric names the break looks ugly, but I'm not sure we can do much about that unless we go through and _manually_ break the metrics, which is not something I want to deal with right now.

@djwfyi @feorlen can you confirm this builds/functions as expected on the OSX side of things?

**Review by ravindk89 — APPROVED** [review]

**Comment by ravindk89** [comment]
Once one other docs team ensures this builds w/o issues on another arch, we're good to roll this out

**Comment by feorlen** [comment]
Confirm macOS build is better 👍🏻

**Pull request merged**
