### PR TITLE
Add docs switch menu

### PR DESCRIPTION
**Pull request by rushenn**
Fixes https://github.com/minio/docs/issues/842

Also made some changes to the dark-mode/read-mode icons to maintain the consistency with KES docs UI. 

**Preview:**
Screenshot 2023-06-15 at 14 19 32

Screenshot 2023-06-15 at 14 19 36

**Updating the list:**

Edit the `docs` array in `default.conf.py@268`.

### CODE REVIEW

**Comment by rushenn** [comment]
@djwfyi Is there a link available for the DirectPV documentation site, let me know what to do with DirectPV entry.

**Comment by djwfyi** [comment]
It will be min.io/docs/directpv, but they are not ready yet. I'd suggest commenting it out for now.

**Comment by rushenn** [comment]
@djwfyi Commented the DirectPV entry for now, PTAL.

**Review by djwfyi — CHANGES_REQUESTED** [review]
I'm not a huge fan of putting it next to the logo, above the top nav.
I think it works fine on the two smaller break points, but not for the full desktop.

For the widest breakpoint, can we put it on the platform nav, the way Oscar had it in the original mockup?
There, or possibly at the top of the left nav.
@ravindk89 and @feorlen Any thoughts?

Staged: http://192.241.195.202:9000/staging/docs-switch/index.html

**Comment by djwfyi** [comment]
I think the top nav needs to stay consistent across the MinIO website, blog, and all docs sites.

**Comment by rushenn** [comment]
@djwfyi Sure, I can move the menu to the platform bar like in the mockup given by Oscar.

**Comment by djwfyi** [comment]
Just for convenience, the link to Oscar's design is https://xd.adobe.com/view/ef6838e9-6f88-4827-8804-b10f40b17d88-ba3b/screen/01304849-dae7-46f1-bdab-324c7d7b8bc2.

**Comment by rushenn** [comment]
> Just for convenience, the link to Oscar's design is https://xd.adobe.com/view/ef6838e9-6f88-4827-8804-b10f40b17d88-ba3b/screen/01304849-dae7-46f1-bdab-324c7d7b8bc2.

Great, I will work on it @djwfyi

**Comment by ravindk89** [comment]
Yes I think we have to conform to Oscar's design. That also had internal approval, so lets focus that and then move from there

**Comment by rushenn** [comment]
@djwfyi @ravindk89 Update menu placement, PTAL.

**Pull request merged**
